version: "3.2"
services:
  vscode:
    image: codercom/code-server:latest 
    restart: always
    volumes:
      - "${PROJECT_ROOT}:/home/coder/project"
      - ".config:/home/coder/.config"
    networks:
      - frontend
    container_name: ${VSCODE_CONTAINER_NAME}
    ports:
      - "${VSCODE_PORT}:8080"
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: ${PHP_CONTAINER_NAME}
    links:
     - mysql
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    links:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: ${APACHE_CONTAINER_NAME}
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
  # The default MySQL installation only creates the "root" administrative account
  # create new users using docker-compose exec
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: ${MYSQL_CONTAINER_NAME}
  phpmyadmin:
    depends_on:
      - mysql
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"   
      UPLOAD_LIMIT: "500M"
    networks:
      - backend
    volumes:
      - /sessions
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
networks:
  frontend:
  backend:
volumes:
    data: